[project]
name = "adaptive"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "ansible-runner>=2.4.2",
    "fastapi>=0.135.1",
    "gunicorn>=25.1.0",
    "proxmoxer>=2.2.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.40.0",
]
