proxmox_url             = "https://10.0.0.10:8006/api2/json"
proxmox_username        = "root@pam"
proxmox_password           = "adaptive"
proxmox_skip_tls_verify = true
proxmox_node            = "pve-01"
proxmox_storage         = "local-lvm"
iso_storage_pool        = "local"
iso_file                = "local:iso/Windows_2022.iso"
virtio_iso_file         = "local:iso/virtio-win-0.1.285.iso"
vm_id                   = 9022 
vm_name                 = "tpl-windows-server-2022"
template_description    = "Windows Server 2022 Template"
vm_cpu_cores            = 2
vm_cpu_sockets          = 1
vm_memory               = 4096
vm_disk_size            = "32G"
network_bridge          = "vmbr0"
winrm_username          = "Administrator"
winrm_password   = "Root123!"
vm_ip            = "10.0.0.50"
vm_prefix_length = "24"
vm_gateway       = "10.0.0.1"
vm_dns           = "10.0.0.1"
computer_name    = "WIN-TEMPLATE"
timezone         = "Romance Standard Time"
os_image_index   = "2"