"""initial

Revision ID: fe386d5f07c5
Revises: 
Create Date: 2026-03-06 15:07:58.493131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe386d5f07c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domains_id'))

    op.drop_table('domains')
    with op.batch_alter_table('forests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forests_id'))

    op.drop_table('forests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    op.drop_table('applied_vulnerabilities')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_id'))

    op.drop_table('servers')
    op.drop_table('vulnerability_templates')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_deployed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('vulnerability_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('powershell_template', sa.TEXT(), nullable=False),
    sa.Column('required_params', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('servers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('forest_id', sa.INTEGER(), nullable=True),
    sa.Column('domain_id', sa.INTEGER(), nullable=True),
    sa.Column('fqdn', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_dc', sa.BOOLEAN(), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=15), nullable=True),
    sa.Column('vm_id', sa.INTEGER(), nullable=True),
    sa.Column('gateway', sa.VARCHAR(length=15), nullable=True),
    sa.Column('dns', sa.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['forest_id'], ['forests.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_id'), ['id'], unique=False)

    op.create_table('applied_vulnerabilities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('source_user_id', sa.INTEGER(), nullable=True),
    sa.Column('target_user_id', sa.INTEGER(), nullable=True),
    sa.Column('params', sa.TEXT(), nullable=True),
    sa.Column('generated_script', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['vulnerability_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('forest_id', sa.INTEGER(), nullable=True),
    sa.Column('domain_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['forest_id'], ['forests.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('forests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('fqdn', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forests_id'), ['id'], unique=False)

    op.create_table('domains',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('forest_id', sa.INTEGER(), nullable=True),
    sa.Column('fqdn', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['forest_id'], ['forests.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domains_id'), ['id'], unique=False)

    # ### end Alembic commands ###
